url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Métadictionnaire" # the name of your site, e.g. ACME Corp.
description: "Métadictionnaire multilingue de la bibliothèque numérique Medica"
