url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Métadictionnaire médical multilingue de la bibliothèque numérique Medica" # the name of your site, e.g. ACME Corp.
description: "Bienvenue sur la page GitHub du Métadictionnaire"
