menu:
- {name: 'interface', url: 'https://www.biusante.parisdescartes.fr/histoire/medica/metadictionnaire/'}
- {name: 'à propos', url: 'https://www.biusante.parisdescartes.fr/histoire/medica/presentation-metadictionnaire.php'}
- {name: 'corpus', url: 'https://www.biusante.parisdescartes.fr/histoire/medica/corpus-metadictionnaire.php'}

social:
- {icon: 'github', link: 'https://github.com/biusante'}
